apiVersion: v1
kind: Pod
metadata:
    name: flaskapp
    labels:
        app: flaskapp
spec:
    containers:
        - image: maxmax89/webapp:v2
          name: flaskapp
          ports:
              - containerPort: 5000
          resources:
            requests:
                memory: "64Mi"
                cpu: "250m"
            limits:
                memory: "128Mi"
                cpu: "500m"