apiVersion: v1
kind: Pod
metadata:
    name: flaskapp
    labels:
        app: flaskapp
spec:
    containers:
        - image: docker.pkg.github.com/made-ml-in-prod-2021/maksm89/webapp:v2
          name: flaskapp
          ports:
              - containerPort: 5000 
    imagePullSecrets:
        - name: readpack